  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        run: |
          python -m pip install aqtinstall
          python -m aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir ${{ runner.workspace }}/Qt
        shell: bash
      - name: Set PATH
        run: echo "${{ runner.workspace }}/Qt/5.15.2/mingw81/bin" >> $GITHUB_PATH
        shell: bash
      # 编译...

  build-ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        run: |
          python -m pip install aqtinstall
          python -m aqt install-qt linux desktop 5.15.2 gcc_64 --outputdir ${{ runner.workspace }}/Qt
        shell: bash
      - name: Set PATH
        run: echo "${{ runner.workspace }}/Qt/5.15.2/gcc_64/bin" >> $GITHUB_PATH
        shell: bash
      # 编译...
