- name: Install Qt
  uses: actions/setup-qt@v1
  with:
    version: '5.15.2'
    host: 'windows'
    target: 'desktop'
    arch: 'win64_mingw81'
    modules: 'qtbase'   # 只装基础，不装额外模块，先让编译通过
    tools: 'tools_ifw'
